name: weatherflutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^8.2.0
  dio: ^4.0.4
  json_annotation: ^4.4.0
  retrofit: ^3.0.1+1
  get: ^4.6.1
  flutter_spinkit: ^5.1.0
  lottie: ^1.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.1.7
  json_serializable: '>4.4.0'

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900